---
- name: Crear usuarios y grupos en sistemas Linux
  hosts: "{{ hosts }}"
  become: true

  vars:
    user: "{{ user }}"
    group: "{{ group }}"
    contra: "{{ contra }}"

  tasks:

    - name: Crear grupos si no existen
      group:
        name: "{{ group }}"
        state: present

    - name: Crear usuarios y asignarlos a sus grupos
      user:
        name: "{{ user }}"
        group: "{{ group }}"
        password: "{{ contra | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present
      register: user_creation

    - name: Mostrar creacion.
      debug:
        var: user_creation

